apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: your-image:tag
        ports:
        - containerPort: 8000
        env:
        - name: PREFECT_API_URL
          value: "http://172.17.0.1:4200"
        - name: MLFLOW_TRACKING_URI
          value: "http://172.17.0.1:5000"
